SELECT
    SUM(CASE 
            WHEN C.HALF_YEAR = 1 THEN C.SCORE 
            WHEN C.HALF_YEAR = 2 THEN C.SCORE 
            ELSE 0 
        END) AS SCORE,
    A.EMP_NO, 
    A.EMP_NAME, 
    A.POSITION, 
    A.EMAIL
FROM 
    HR_EMPLOYEES A 
JOIN 
    HR_GRADE C ON A.EMP_NO = C.EMP_NO
JOIN 
    HR_DEPARTMENT B ON A.DEPT_ID = B.DEPT_ID
GROUP BY 
    A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
ORDER BY 
    SCORE DESC
LIMIT 1;
